backend/config/routes.rb
Rails.application.routes.draw do
  resources :todo_lists
  resources :tasks
  root 'todo_lists#index'

  if Rails.env.test?
    namespace :test do
      post 'database_cleaner/clean' => 'database_cleaner#clean'
      post 'factories' => 'factories#create'
    end
  end
end

backend/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

backend/app/models/task.rb
class Task < ApplicationRecord
  belongs_to :todo_list
end

backend/app/models/todo_list.rb
class TodoList < ApplicationRecord
  has_many :tasks, dependent: :destroy
end

backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

backend/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show; end

  # GET /tasks/new
  def new
    @task = Task.new
    @todo_lists = TodoList.all
  end

  # GET /tasks/1/edit
  def edit
    @todo_lists = TodoList.all
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        @todo_lists = TodoList.all
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def task_params
    params.require(:task).permit(:title, :todo_list_id)
  end
end

backend/app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: %i[show edit update destroy]

  # GET /todo_lists or /todo_lists.json
  def index
    @todo_lists = TodoList.includes(:tasks).all
  end

  # GET /todo_lists/1 or /todo_lists/1.json
  def show; end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit; end

  # POST /todo_lists or /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to todo_list_url(@todo_list), notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1 or /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to todo_list_url(@todo_list), notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1 or /todo_lists/1.json
  def destroy
    @todo_list.destroy

    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_todo_list
    @todo_list = TodoList.includes(:tasks).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def todo_list_params
    params.require(:todo_list).permit(:name)
  end
end

backend/app/helpers/application_helper.rb
module ApplicationHelper
end

backend/app/helpers/tasks_helper.rb
module TasksHelper
end

backend/app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Backend</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

backend/app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>
      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :todo_list, style: "display: block" %>
    <%= form.select :todo_list_id, todo_lists.map { |todo_list| [todo_list.name, todo_list.id] } %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <p>
    <strong>Title:</strong>
    <%= task.title %>
  </p>

</div>

backend/app/views/tasks/edit.html.erb
<h1>Editing task</h1>
<%= render "form", task: @task, todo_lists: @todo_lists %>
<br>
<div>
  <%= link_to "Show this task", @task %> |
  <%= link_to "Back to tasks", tasks_path %>
</div>

backend/app/views/tasks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tasks</h1>

<div id="tasks">
  <% @tasks.each do |task| %>
    <%= render task %>
    <p>
      <%= link_to "Show this task", task %>
    </p>
  <% end %>
</div>

<%= link_to "New task", new_task_path %>

backend/app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render "form", task: @task, todo_lists: @todo_lists %>

<br>

<div>
  <%= link_to "Back to tasks", tasks_path %>
</div>

backend/app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @task %>

<div>
  <%= link_to "Edit this task", edit_task_path(@task) %> |
  <%= link_to "Back to tasks", tasks_path %>

  <%= button_to "Destroy this task", @task, method: :delete %>
</div>

backend/app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list) do |form| %>
  <% if todo_list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
        <% todo_list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/todo_lists/_todo_list.html.erb
<div id="<%= dom_id todo_list %>">
  <p>
    <strong>Name:</strong>
    <%= todo_list.name %>
  </p>

</div>

backend/app/views/todo_lists/edit.html.erb
<h1>Editing todo list</h1>

<%= render "form", todo_list: @todo_list %>

<br>

<div>
  <%= link_to "Show this todo list", @todo_list %> |
  <%= link_to "Back to todo lists", todo_lists_path %>
</div>

backend/app/views/todo_lists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Todo lists</h1>

<div id="todo_lists">
  <% @todo_lists.each do |todo_list| %>
    <%= render todo_list %>
    <p>
      <%= link_to "Show this todo list", todo_list %>
    </p>
  <% end %>
</div>

<%= link_to "New todo list", new_todo_list_path %>

backend/app/views/todo_lists/new.html.erb
<h1>New todo list</h1>

<%= render "form", todo_list: @todo_list %>

<br>

<div>
  <%= link_to "Back to todo lists", todo_lists_path %>
</div>

backend/app/views/todo_lists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @todo_list %>

<div>
  <%= link_to "Edit this todo list", edit_todo_list_path(@todo_list) %> |
  <%= link_to "Back to todo lists", todo_lists_path %>

  <%= button_to "Destroy this todo list", @todo_list, method: :delete %>
</div>